### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by KeisukeShima** [tier4/ros-metrics-reporter#70]
- [ ] Generate reports for modified files in pull requests.
- [ ] Add the ability to get the coverage for each type of test.
- [ ] Change the backend framework to MkDocs.
- [ ] Change the layout of the page to center-aligned.
- [ ] Add the ability to sort tables.
